// <auto-generated />
using Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(SimulacaoDbContext))]
    partial class SimulacaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Infra.Persistence.Entities.ParcelaData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResultadoSimulacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorAmortizacao")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorJuros")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPrestacao")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultadoSimulacaoId");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("Infra.Persistence.Entities.ResultadoSimulacaoData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("SimulacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SimulacaoId");

                    b.ToTable("ResultadosSimulacao");
                });

            modelBuilder.Entity("Infra.Persistence.Entities.SimulacaoData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("IdSimulacao")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxaJuros")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("Infra.Persistence.Entities.ParcelaData", b =>
                {
                    b.HasOne("Infra.Persistence.Entities.ResultadoSimulacaoData", "ResultadoSimulacao")
                        .WithMany("Parcelas")
                        .HasForeignKey("ResultadoSimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResultadoSimulacao");
                });

            modelBuilder.Entity("Infra.Persistence.Entities.ResultadoSimulacaoData", b =>
                {
                    b.HasOne("Infra.Persistence.Entities.SimulacaoData", "Simulacao")
                        .WithMany("Resultados")
                        .HasForeignKey("SimulacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacao");
                });

            modelBuilder.Entity("Infra.Persistence.Entities.ResultadoSimulacaoData", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Infra.Persistence.Entities.SimulacaoData", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
